# Название пайплайна
name: CI Pipeline

# Когда запускать пайплайн
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Глобальные переменные окружения
env:
  PYTHON_VERSION: '3.12.3'
  POSTGRES_VERSION: '8.2'

# Джобы
jobs:
  # 1. УСТАНОВКА И ПРОВЕРКА ЗАВИСИМОСТЕЙ
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Check requirements.txt exists
        id: check_req
        run: |
          if [ -f "requirements.txt" ]; then
            echo "requirements.txt exists"
            echo "has_req=true" >> $GITHUB_OUTPUT
          else
            echo "requirements.txt not found"
            echo "has_req=false" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        if: steps.check_req.outputs.has_req == 'true'
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install test dependencies
        run: |
          pip install pytest pytest-flask
          pip install flask-sqlalchemy flask-login

      - name: Verify installation
        run: |
          python --version
          pip list | grep -E "(pytest|flask)"

  # 2. ЛИНТИНГ
  lint:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install pylint
        run: pip install pylint

      - name: Run pylint on Python files
        run: |
          # Ищем все Python файлы в проекте
          find . -name "*.py" -not -path "./venv/*" -not -path "./.env/*" | head -20 > python_files.txt
          echo "Python files found:"
          cat python_files.txt

          # Запускаем pylint для основных файлов
          for file in app.py app/init.py app/models.py app/routes.py; do
            if [ -f "$file" ]; then
              echo "Linting $file"
              pylint "$file" --exit-zero || true
            fi
          done

      - name: Check Python syntax
        run: |
          echo "Checking Python syntax..."
          python -m py_compile app/init.py || true
          python -m py_compile app/models.py || true
          python -m py_compile app/routes.py || true

  # 3. ТЕСТИРОВАНИЕ
  test:
    runs-on: ubuntu-latest
    needs: setup

    # Сервис PostgreSQL для тестов
    services:
      postgres:
        image: postgres:${{ env.POSTGRES_VERSION }}
        env:
          POSTGRES_PASSWORD: cat
          POSTGRES_USER: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432

    env:
      DATABASE_URL: postgresql://postgres:cat@localhost:5433/nutrition_db_test
      SECRET_KEY: test-secret-key-for-ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          fi
          pip install pytest pytest-flask psycopg2-binary

      - name: Wait for PostgreSQL
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          sleep 10

      - name: Run basic tests
        run: |
          echo "Running basic tests..."
          python tests/test_basic.py

      - name: Run model tests
        run: |
          echo "Running model tests..."
          python tests/test_models.py

      - name: Run calculation tests
        run: |
          echo "Running calculation tests..."
          python tests/test_calculation.py

      - name: Run simplified route tests
        run: |
          echo "Running route tests..."
          python tests/test_routes.py

      - name: Run pytest tests
        run: |
          echo "Running pytest tests..."
          python -m pytest tests/ -v --tb=short || echo "Some tests may have failed"

      - name: Create test report
        run: |
          echo "Test Results Summary:" > test-report.txt
          echo "=====================" >> test-report.txt
          echo "" >> test-report.txt

          # Запускаем каждый тестовый файл и собираем вывод
          for test_file in tests/test_*.py; do
            if [ -f "$test_file" ]; then
              echo "Running $test_file" >> test-report.txt
              python "$test_file" 2>&1 | tail -20 >> test-report.txt
              echo "" >> test-report.txt
              echo "---" >> test-report.txt
              echo "" >> test-report.txt
            fi
          done

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-report.txt

  # 4. ПРОВЕРКА СТИЛЯ КОДА
  style:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install black
        run: pip install black

      - name: Check code formatting with black
        run: |
          echo "Checking code formatting..."
          black --check --diff app/ tests/ || echo "Code formatting check completed"

      - name: Count lines of code
        run: |
          echo "Lines of code statistics:"
          find . -name "*.py" -not -path "./venv/*" -not -path "./.env/*" -exec wc -l {} + | tail -1

  # 5. СБОРКА И ВАЛИДАЦИЯ
  build:
    runs-on: ubuntu-latest
    needs: [test, lint, style]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Validate project structure
        run: |
          echo "Validating project structure..."

          # Проверяем обязательные файлы
          required_files=("app/__init__.py" "app/models.py" "app/user_routes.py" "app/auth.py" "app/forms.py" "app/admin_routes.py" "app/calculation.py")
          for file in "${required_files[@]}"; do
            if [ -f "$file" ]; then
              echo "OK: $file exists"
            else
              echo "ERROR: $file not found"
              exit 1
            fi
          done

          # Проверяем тесты
          if [ -d "tests" ]; then
            echo "OK: tests directory exists"
            test_count=$(find tests -name "test_*.py" | wc -l)
            echo "Found $test_count test files"
          else
            echo "WARNING: tests directory not found"
          fi

      - name: Check imports
        run: |
          echo "Checking imports..."
          python -c "
          try:
              from app import create_app
              print('OK: create_app imported')
          except ImportError as e:
              print(f'ERROR: {e}')

          try:
              from app.models import User, Ingredient, Recipe
              print('OK: models imported')
          except ImportError as e:
              print(f'ERROR: {e}')

          try:
              from app.calculation import calculate_optimal_diet
              print('OK: calculation functions imported')
          except ImportError as e:
              print(f'ERROR: {e}')
          "

      - name: Create build summary
        run: |
          echo "Build Summary" > build-summary.txt
          echo "=============" >> build-summary.txt
          echo "" >> build-summary.txt
          echo "Project: Что готовить" >> build-summary.txt
          echo "Branch: ${{ github.ref_name }}" >> build-summary.txt
          echo "Commit: ${{ github.sha }}" >> build-summary.txt
          echo "Timestamp: $(date)" >> build-summary.txt
          echo "" >> build-summary.txt

          # Собираем информацию о файлах
          echo "Project Structure:" >> build-summary.txt
          find . -name "*.py" -not -path "./venv/*" -not -path "./.env/*" | sort >> build-summary.txt

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            build-summary.txt
            requirements.txt

  # 6. ИТОГОВЫЙ ОТЧЕТ
  report:
    runs-on: ubuntu-latest
    needs: [lint, test, style, build]
    if: always()

    steps:
      - name: Generate final report
        run: |
          echo "CI/CD Pipeline Report" > pipeline-report.txt
          echo "=====================" >> pipeline-report.txt
          echo "" >> pipeline-report.txt
          echo "Repository: ${{ github.repository }}" >> pipeline-report.txt
          echo "Workflow: ${{ github.workflow }}" >> pipeline-report.txt
          echo "Run ID: ${{ github.run_id }}" >> pipeline-report.txt
          echo "Branch: ${{ github.ref_name }}" >> pipeline-report.txt
          echo "Commit: ${{ github.sha }}" >> pipeline-report.txt
          echo "Triggered by: ${{ github.event_name }}" >> pipeline-report.txt
          echo "" >> pipeline-report.txt

          echo "Job Results:" >> pipeline-report.txt
          echo "-----------" >> pipeline-report.txt
          echo "Setup: ${{ needs.setup.result }}" >> pipeline-report.txt
          echo "Lint: ${{ needs.lint.result }}" >> pipeline-report.txt
          echo "Test: ${{ needs.test.result }}" >> pipeline-report.txt
          echo "Style: ${{ needs.style.result }}" >> pipeline-report.txt
          echo "Build: ${{ needs.build.result }}" >> pipeline-report.txt
          echo "" >> pipeline-report.txt

          echo "Summary:" >> pipeline-report.txt
          echo "-------" >> pipeline-report.txt

          # Определяем общий статус
          if [[ "${{ needs.test.result }}" == "success" ]] && \
             [[ "${{ needs.lint.result }}" == "success" ]] && \
             [[ "${{ needs.build.result }}" == "success" ]]; then
            echo "All checks passed successfully" >> pipeline-report.txt
            echo "STATUS=PASSED" >> $GITHUB_ENV
          else
            echo "Some checks failed" >> pipeline-report.txt
            echo "STATUS=FAILED" >> $GITHUB_ENV
          fi

      - name: Upload final report
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-report
          path: pipeline-report.txt

      - name: Output final status
        run: |
          echo "Pipeline completed with status: $STATUS"
          if [[ "$STATUS" == "FAILED" ]]; then
            exit 1
          fi